Continues correcting JSDoc types for Typescript tooling compatibility
w3c/aria-at-automation-harness pull request #58
Opened 2024-07-09 22:49 UTC by ChrisC

2024-07-09 23:06 UTC, ChrisC commented
@jugglinmike there are two clusters of files remaining that would complete the[ typescript formalization work](https://github.com/w3c/aria-at-automation-harness/issues/3): 
[shared/job](https://github.com/w3c/aria-at-automation-harness/blob/main/src/shared/job.js) and the [source](https://github.com/w3c/aria-at-automation-harness/blob/main/src/shared/file-record.js) and [test](https://github.com/w3c/aria-at-automation-harness/blob/main/src/shared/tests/file-record.js) files for `shared/file-record`.

I anticipate that fixing the types for both of these modules will be a bit difficult and probably require some amount of re-factoring. That being the case, I'm wondering if we might want to hold off on correcting these types for now, since a bigger refactor to simplify the harness is coming. 

In particular, I'm wondering if we might want to do away with the `shared/jobs` abstraction altogether? I'm a little less clear on whether or not we may need the `file-record` abstraction going forward, but I do think this module would benefit from a substantial simplification if we do decide to keep it. 

@jugglinmike @gnarf It might be a good idea for us to plan out that bigger refactor in a little more detail, so that we can make sure to only correct the types we know we'll continue using after the refactor?

2024-07-10 15:19 UTC, jugglinmike requested changes
> @jugglinmike @gnarf It might be a good idea for us to plan out that bigger refactor in a little more detail, so that we can make sure to only correct the types we know we'll continue using after the refactor?

Agreed. We prioritized this work because we'd have more confidence refactoring a well-typed project. There's no sense spending a lot of time fixing doomed files.

2024-07-10 15:19 UTC, jugglinmike commented on src/shared/iterate-emitter.js
>   * @param {EventEmitter} emitter
We can avoid creating an unused binding like this:

```suggestion
/**
 * @param {import("events").EventEmitter} emitter
```

That way, any linting process [we might add](https://github.com/w3c/aria-at-automation-harness/issues/59) doesn't necessarily need to be aware of JSDoc.

2024-07-10 17:49 UTC, ChrisC commented
> 
> Agreed. We prioritized this work because we'd have more confidence refactoring a well-typed project. There's no sense spending a lot of time fixing doomed files.

Got it. In that case, I'll go ahead and submit this PR and we'll determine later whether or not those last files will make it into the upcoming refactor.

2024-07-10 20:17 UTC, jugglinmike approved these changes
Thanks, Chris!

2024-07-10 20:19 UTC, merged